namespace RForgeTest.Client.TestModels;

public class GetFakeUsers : IGetFakeUsers
{
    public IEnumerable<UserRowData> Get()
    {
        return
        [
            new UserRowData() { Id = 1, FirstName = "Emily", LastName="Johnson", Email = "emily.johnson@example.com" },
            new UserRowData() { Id = 2, FirstName = "Michael", LastName="Williams", Email = "michael.williams@example.net" },
            new UserRowData() { Id = 3, FirstName = "Sophia", LastName="Davis", Email = "sophia.davis@example.org" },
            new UserRowData() { Id = 4, FirstName = "Jacob", LastName="Miller", Email = "jacob.miller@example.com" },
            new UserRowData() { Id = 5, FirstName = "Ava", LastName="Anderson", Email = "ava.anderson@example.net" },
            new UserRowData() { Id = 6, FirstName = "William", LastName="Wilson", Email = "william.wilson@example.org" },
            new UserRowData() { Id = 7, FirstName = "Isabella", LastName="Moore", Email = "isabella.moore@example.com" },
            new UserRowData() { Id = 8, FirstName = "Daniel", LastName="Taylor", Email = "daniel.taylor@example.net" },
            new UserRowData() { Id = 9, FirstName = "Mia", LastName="Thomas", Email = "mia.thomas@example.org" },
            new UserRowData() { Id = 10, FirstName = "Ethan", LastName="Jackson", Email = "ethan.jackson@example.com" },
            new UserRowData() { Id = 11, FirstName = "Olivia", LastName="White", Email = "olivia.white@example.com" },
            new UserRowData() { Id = 12, FirstName = "Joseph", LastName="Harris", Email = "joseph.harris@example.net" },
            new UserRowData() { Id = 13, FirstName = "Emma", LastName="Martin", Email = "emma.martin@example.org" },
            new UserRowData() { Id = 14, FirstName = "Noah", LastName="Thompson", Email = "noah.thompson@example.com" },
            new UserRowData() { Id = 15, FirstName = "Abigail", LastName="Garcia", Email = "abigail.garcia@example.net" },
            new UserRowData() { Id = 16, FirstName = "Liam", LastName="Martinez", Email = "liam.martinez@example.org" },
            new UserRowData() { Id = 17, FirstName = "Avery", LastName="Robinson", Email = "avery.robinson@example.com" },
            new UserRowData() { Id = 18, FirstName = "Benjamin", LastName="Clark", Email = "benjamin.clark@example.net" },
            new UserRowData() { Id = 19, FirstName = "Amelia", LastName="Rodriguez", Email = "amelia.rodriguez@example.org" },
            new UserRowData() { Id = 20, FirstName = "Mason", LastName="Lewis", Email = "mason.lewis@example.com" },
            new UserRowData() { Id = 21, FirstName = "Harper", LastName="Lee", Email = "harper.lee@example.net" },
            new UserRowData() { Id = 22, FirstName = "Elijah", LastName="Walker", Email = "elijah.walker@example.org" },
            new UserRowData() { Id = 23, FirstName = "Charlotte", LastName="Hall", Email = "charlotte.hall@example.com" },
            new UserRowData() { Id = 24, FirstName = "James", LastName="Allen", Email = "james.allen@example.net" },
            new UserRowData() { Id = 25, FirstName = "Scarlett", LastName="Young", Email = "scarlett.young@example.org" },
            new UserRowData() { Id = 26, FirstName = "Henry", LastName="Hernandez", Email = "henry.hernandez@example.com" },
            new UserRowData() { Id = 27, FirstName = "Elizabeth", LastName="King", Email = "elizabeth.king@example.net" },
            new UserRowData() { Id = 28, FirstName = "Alexander", LastName="Wright", Email = "alexander.wright@example.org" },
            new UserRowData() { Id = 29, FirstName = "Sofia", LastName="Lopez", Email = "sofia.lopez@example.com" },
            new UserRowData() { Id = 30, FirstName = "Matthew", LastName="Hill", Email = "matthew.hill@example.net" },
            new UserRowData() { Id = 31, FirstName = "Layla", LastName="Scott", Email = "layla.scott@example.org" },
            new UserRowData() { Id = 32, FirstName = "Andrew", LastName="Green", Email = "andrew.green@example.com" },
            new UserRowData() { Id = 33, FirstName = "Lillian", LastName="Adams", Email = "lillian.adams@example.net" },
            new UserRowData() { Id = 34, FirstName = "Joshua", LastName="Baker", Email = "joshua.baker@example.org" },
            new UserRowData() { Id = 35, FirstName = "Nora", LastName="Gonzalez", Email = "nora.gonzalez@example.com" },
            new UserRowData() { Id = 36, FirstName = "Lucas", LastName="Nelson", Email = "lucas.nelson@example.net" },
            new UserRowData() { Id = 37, FirstName = "Grace", LastName="Carter", Email = "grace.carter@example.org" },
            new UserRowData() { Id = 38, FirstName = "David", LastName="Mitchell", Email = "david.mitchell@example.com" },
            new UserRowData() { Id = 39, FirstName = "Chloe", LastName="Perez", Email = "chloe.perez@example.net" },
            new UserRowData() { Id = 40, FirstName = "Caleb", LastName="Roberts", Email = "caleb.roberts@example.org" },
            new UserRowData() { Id = 41, FirstName = "Penelope", LastName="Turner", Email = "penelope.turner@example.com" },
            new UserRowData() { Id = 42, FirstName = "Ryan", LastName="Phillips", Email = "ryan.phillips@example.net" },
            new UserRowData() { Id = 43, FirstName = "Riley", LastName="Campbell", Email = "riley.campbell@example.org" },
            new UserRowData() { Id = 44, FirstName = "Nathan", LastName="Parker", Email = "nathan.parker@example.com" },
            new UserRowData() { Id = 45, FirstName = "Hazel", LastName="Evans", Email = "hazel.evans@example.net" },
            new UserRowData() { Id = 46, FirstName = "Dylan", LastName="Edwards", Email = "dylan.edwards@example.org" },
            new UserRowData() { Id = 47, FirstName = "Victoria", LastName="Collins", Email = "victoria.collins@example.com" },
            new UserRowData() { Id = 48, FirstName = "Gabriel", LastName="Stewart", Email = "gabriel.stewart@example.net" },
            new UserRowData() { Id = 49, FirstName = "Zoe", LastName="Sanchez", Email = "zoe.sanchez@example.org" },
            new UserRowData() { Id = 50, FirstName = "Logan", LastName="Morris", Email = "logan.morris@example.com" },
            new UserRowData() { Id = 51, FirstName = "Lily", LastName="Rogers", Email = "lily.rogers@example.net" },
            new UserRowData() { Id = 52, FirstName = "Isaac", LastName="Reed", Email = "isaac.reed@example.org" },
            new UserRowData() { Id = 53, FirstName = "Evelyn", LastName="Cook", Email = "evelyn.cook@example.com" },
            new UserRowData() { Id = 54, FirstName = "Levi", LastName="Morgan", Email = "levi.morgan@example.net" },
            new UserRowData() { Id = 55, FirstName = "Aubrey", LastName="Bell", Email = "aubrey.bell@example.org" },
            new UserRowData() { Id = 56, FirstName = "Jayden", LastName="Murphy", Email = "jayden.murphy@example.com" },
            new UserRowData() { Id = 57, FirstName = "Adalyn", LastName="Bailey", Email = "adalyn.bailey@example.net" },
            new UserRowData() { Id = 58, FirstName = "Owen", LastName="Rivera", Email = "owen.rivera@example.org" },
            new UserRowData() { Id = 59, FirstName = "Ariana", LastName="Cooper", Email = "ariana.cooper@example.com" },
            new UserRowData() { Id = 60, FirstName = "John", LastName="Richardson", Email = "john.richardson@example.net" },
            new UserRowData() { Id = 61, FirstName = "Mackenzie", LastName="Cox", Email = "mackenzie.cox@example.org" },
            new UserRowData() { Id = 62, FirstName = "Samuel", LastName="Howard", Email = "samuel.howard@example.com" },
            new UserRowData() { Id = 63, FirstName = "Madeline", LastName="Ward", Email = "madeline.ward@example.net" },
            new UserRowData() { Id = 64, FirstName = "Jack", LastName="Torres", Email = "jack.torres@example.org" },
            new UserRowData() { Id = 65, FirstName = "Kaylee", LastName="Peterson", Email = "kaylee.peterson@example.com" },
            new UserRowData() { Id = 66, FirstName = "Luke", LastName="Gray", Email = "luke.gray@example.net" },
            new UserRowData() { Id = 67, FirstName = "Alexa", LastName="Ramirez", Email = "alexa.ramirez@example.org" },
            new UserRowData() { Id = 68, FirstName = "Jackson", LastName="James", Email = "jackson.james@example.com" },
            new UserRowData() { Id = 69, FirstName = "Makayla", LastName="Watson", Email = "makayla.watson@example.net" },
            new UserRowData() { Id = 70, FirstName = "Carter", LastName="Brooks", Email = "carter.brooks@example.org" },
            new UserRowData() { Id = 71, FirstName = "Kennedy", LastName="Kelly", Email = "kennedy.kelly@example.com" },
            new UserRowData() { Id = 72, FirstName = "Grayson", LastName="Sanders", Email = "grayson.sanders@example.net" },
            new UserRowData() { Id = 73, FirstName = "Ruby", LastName="Price", Email = "ruby.price@example.org" },
            new UserRowData() { Id = 74, FirstName = "Callie", LastName="Bennett", Email = "callie.bennett@example.com" },
            new UserRowData() { Id = 75, FirstName = "Isaac", LastName="Barnes", Email = "isaac.barnes@example.net" },
            new UserRowData() { Id = 76, FirstName = "Savannah", LastName="Ross", Email = "savannah.ross@example.org" },
            new UserRowData() { Id = 77, FirstName = "Wyatt", LastName="Henderson", Email = "wyatt.henderson@example.com" },
            new UserRowData() { Id = 78, FirstName = "Elsie", LastName="Coleman", Email = "elsie.coleman@example.net" },
            new UserRowData() { Id = 79, FirstName = "Colton", LastName="Jenkins", Email = "colton.jenkins@example.org" },
            new UserRowData() { Id = 80, FirstName = "Paisley", LastName="Perry", Email = "paisley.perry@example.com" },
            new UserRowData() { Id = 81, FirstName = "Luca", LastName="Powell", Email = "luca.powell@example.net" },
            new UserRowData() { Id = 82, FirstName = "Skylar", LastName="Long", Email = "skylar.long@example.org" },
            new UserRowData() { Id = 83, FirstName = "Josiah", LastName="Patterson", Email = "josiah.patterson@example.com" },
            new UserRowData() { Id = 84, FirstName = "Natalie", LastName="Hughes", Email = "natalie.hughes@example.net" },
            new UserRowData() { Id = 85, FirstName = "Jordan", LastName="Flores", Email = "jordan.flores@example.org" },
            new UserRowData() { Id = 86, FirstName = "Naomi", LastName="Washington", Email = "naomi.washington@example.com" },
            new UserRowData() { Id = 87, FirstName = "Dominic", LastName="Butler", Email = "dominic.butler@example.net" },
            new UserRowData() { Id = 88, FirstName = "Camilla", LastName="Simmons", Email = "camilla.simmons@example.org" },
            new UserRowData() { Id = 89, FirstName = "Maximus", LastName="Foster", Email = "maximus.foster@example.com" },
            new UserRowData() { Id = 90, FirstName = "Ariel", LastName="Gonzales", Email = "ariel.gonzales@example.net" },
            new UserRowData() { Id = 91, FirstName = "Luis", LastName="Bryant", Email = "luis.bryant@example.org" },
            new UserRowData() { Id = 92, FirstName = "Addyson", LastName="Alexander", Email = "addyson.alexander@example.com" },
            new UserRowData() { Id = 93, FirstName = "Hudson", LastName="Russell", Email = "hudson.russell@example.net" },
            new UserRowData() { Id = 94, FirstName = "Skyler", LastName="Griffin", Email = "skyler.griffin@example.org" },
            new UserRowData() { Id = 95, FirstName = "Adrian", LastName="Diaz", Email = "adrian.diaz@example.com" },
            new UserRowData() { Id = 96, FirstName = "Stella", LastName="Hayes", Email = "stella.hayes@example.net" },
            new UserRowData() { Id = 97, FirstName = "Jaxon", LastName="Myers", Email = "jaxon.myers@example.org" },
            new UserRowData() { Id = 98, FirstName = "Luna", LastName="Ford", Email = "luna.ford@example.com" },
            new UserRowData() { Id = 99, FirstName = "Isaiah", LastName="Hamilton", Email = "isaiah.hamilton@example.net" },
            new UserRowData() { Id = 100, FirstName = "Aria", LastName="Graham", Email = "aria.graham@example.org" }
        ];
    }
}
